
site_name: Tools and Software Tutorials


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    
theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni



nav:
- Home: home.md

- Dash:
  - Numpy Basics: dash/numpy-basics.md
  - Pandas Basics: dash/pandas-basics.md
  - Plotly Basics : dash/plotly-basics.md

- Flask: 
  - Intro to Flask: flask/flask-concepts.md
  - Creating First Website: flask/first-website.md
  - Dynamic Routing: flask/dynamic-routing.md
